
bluetooth_manager:
  bluetoothctl_path: "/usr/bin/bluetoothctl"
  max_connections: 4
  logging:
    level: "INFO"
    format: "%(asctime)s - %(levelname)s - %(message)s"
    file: "/var/log/bluetooth_manager.log"
