name: Build and Publish on Ubuntu 20.04

on:
  push:
    branches:
      - main  # Triggers the workflow on push events to the main branch.

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04  # Specifies the runner environment.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out the repository code under $GITHUB_WORKSPACE.

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specifies the Python version to use.

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bluez python3-pip  # Installs necessary system packages.

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python3 -m pip install -r requirements.txt
          fi

      - name: Install the package
        run: |
          python3 setup.py install  # Installs the package using setup.py.

      - name: Build the package
        run: |
          python3 setup.py sdist bdist_wheel  # Creates source distribution and wheel.

      - name: Install twine
        run: |
          pip install twine  # Installs twine for uploading packages.

      - name: Publish the package to GitHub Packages
        run: |
          twine upload --repository-url https://pypi.pkg.github.com/LoQiseaking69/ dist/* -u __token__ -p ${{ github.token }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ github.token }}