name: Build and Publish on Windows and Ubuntu

on:
  push:
    branches:
      - main  # Triggers the workflow on push events to the main branch.

jobs:
  build-and-publish-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bluez python3-pip

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python3 -m pip install -r requirements.txt
          fi

      - name: Install the package
        run: |
          python3 setup.py install

      - name: Build wxPython application
        run: |
          python3 -m pip install wxPython
          python3 your_application_script.py

      - name: Publish the Bluetooth package
        run: |
          python3 -m pip install setuptools wheel twine
          python3 setup.py sdist bdist_wheel
          twine upload dist/*

  build-and-publish-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          choco install python3-pip

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt (
            python -m pip install -r requirements.txt
          )

      - name: Install the package
        run: |
          python setup.py install

      - name: Build wxPython application
        run: |
          python -m pip install wxPython
          python your_application_script.py

      - name: Publish the Bluetooth package
        run: |
          python -m pip install setuptools wheel twine
          python setup.py sdist bdist_wheel
          twine upload dist/*