name: Build on Ubuntu 20.04

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-20.04  # Specifies the runner environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Ensures compatibility with the specified Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Updates pip
          python setup.py install  # Installs your Python package and any dependencies

      - name: Execute Build.sh script
        run: |
          chmod +x Build.sh  # Makes sure the script is executable
          ./Build.sh  # Executes your build script
