name: Tests on Ubuntu 22.04

on:
  push:
    branches:
      - main

jobs:
  flake8:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bluez python3-pip
          python3 -m pip install --upgrade pip

      - name: Install the package
        run: |
          python3 -m pip install ".[test]"

      - name: Run flake8 tests
        run: |
          python3 -m flake8 bluetooth_manager
          python3 -m flake8 examples

  mypy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bluez python3-pip
          python3 -m pip install --upgrade pip

      - name: Install the package
        run: |
          python3 -m pip install ".[test,stubs]"

      - name: Run mypy tests
        run: |
          python3 -m mypy bluetooth_manager

  test:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bluez python3-pip
          python3 -m pip install --upgrade pip

      - name: Install the package
        run: |
          python3 -m pip install ".[test]"

      # until tests exist, we simply test by creating the package
      # - name: Run tests
      #   run: |
      #     python3 -m pytest
